name:                llama
version:             0.1.0.0
github:              "githubuser/llama"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/llama#readme>

dependencies:
- base >= 4.7 && < 5
- language-c
- directory
- containers
- split
- MissingH
- process
- fgl

library:
  source-dirs: src

executables:
  llama:
    main:                Main.lhs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - llama

  pinchpoints:
    main:                MainPinchpoints.lhs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -main-is MainPinchpoints
    - -with-rtsopts=-N
    dependencies:
    - llama

  caller-id:
    main:                MainCallerId.lhs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -main-is MainCallerId
    - -with-rtsopts=-N
    dependencies:
    - llama

tests:
  llama-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - llama
